version: '2'

services:
  app:
    ports:
        - "8080:80"
    image: yonh/php:alpine-1.12-apache
    restart: always    
    volumes:
      - .:/app
    environment:
      - WEBAPP_ROOT=public
    networks:
      - apps

networks:
  apps:
    external: true